[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl", "python3"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm install && npx prisma generate"]

[start]
cmd = "node scripts/fix-failed-migration.js && npx prisma migrate deploy && npm start"


